name: ARTSHARE FE USER CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '22'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run tests
  #       run: npm run test

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: success()
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '22'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build the app
  #       run: npm run build

  #     - name: Vercel CLI - Deploy
  #       uses: amondnet/vercel-action@v21
  #       with:
  #         vercel_token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
  #       env:
  #         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
