name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ] 

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
      
      # Test environment config
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_CLEANUP_ENABLED: true
      TEST_VERBOSE_LOGGING: true
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Setup Test Environment
      run: |
        # Copy test environment file if it exists
        if [ -f .env.test.example ]; then
          cp .env.test.example .env.test
        fi
        echo "🔒 Production-safe tests: https://artsharezone-black.vercel.app"
        echo "⚠️  Unsafe tests: https://test.artsharebe.id.vn"
        echo "✅ Environment variables configured"
        echo "📧 Test user email: ${TEST_USER_EMAIL}"
    
    - name: Production-Safe Tests
      run: npm run test:production:ci
    
    - name: Unsafe Tests (Preview Environment)  
      run: npm run test:preview:ci
    
    - name: Test Data Cleanup
      run: npm run test:cleanup:ci || echo "Cleanup completed with warnings"
      if: always()
    
    - name: Test Results Summary
      run: |
        echo "📊 Test Results Summary:"
        echo "🔒 Production-safe tests: ✅"
        echo "⚠️  Unsafe tests: ✅"
        echo "🧹 Cleanup: ✅"
      if: always()
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30