export const canvasSizeOptions = [
  {
    label: '1:1',
    value: '1:1',
    sizes: [
      { label: 'Small (512 x 512)', width: 512, height: 512 },
      { label: 'Medium (1080 x 1080)', width: 1080, height: 1080 },
      { label: 'Large (2048 x 2048)', width: 2048, height: 2048 },
    ],
  },
  {
    label: '16:9',
    value: '16:9',
    sizes: [
      { label: 'Small (640 x 360)', width: 640, height: 360 },
      { label: 'Medium (1280 x 720)', width: 1280, height: 720 },
      { label: 'Large (1920 x 1080)', width: 1920, height: 1080 },
    ],
  },
  {
    label: '4:3',
    value: '4:3',
    sizes: [
      { label: 'Small (800 x 600)', width: 800, height: 600 },
      { label: 'Medium (1024 x 768)', width: 1024, height: 768 },
      { label: 'Large (1600 x 1200)', width: 1600, height: 1200 },
    ],
  },
  {
    label: '3:4',
    value: '3:4',
    sizes: [
      { label: 'Small (600 x 800)', width: 600, height: 800 },
      { label: 'Medium (768 x 1024)', width: 768, height: 1024 },
      { label: 'Large (1200 x 1600)', width: 1200, height: 1600 },
    ],
  },
];

export const smallCanvasByRatio = {
  '1:1': { width: 560, height: 560 },
  '16:9': { width: 996, height: 560 },
  '4:3': { width: 747, height: 560 },
  '3:4': { width: 420, height: 560 },
};

export const fileTypes = [
  { label: 'PNG', value: 'png', color: 'violet-600' },
  { label: 'JPG', value: 'jpg', color: 'indigo-600' },
];

export const ratioMap: Record<string, string> = {
  '1.00': '1:1',
  '1.78': '16:9',
  '1.33': '4:3',
  '0.75': '3:4',
};

export const designSamples: Record<string, NewDesign> = {
  sample1: {
    canvas: { width: 420, height: 560 },
    finalCanvas: { width: 768, height: 1024 },
    layers: [
      {
        type: 'image',
        id: crypto.randomUUID(),
        src: '',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 0,
        y: 0,
        width: 420,
        height: 560,
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        zIndex: 0,
        isLocked: false,
      },
      {
        type: 'image',
        id: 'base-layer',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754760808/artshare-asset/design-sample/sample-1/pngtree-pink-beautiful-texture-background-picture-image_1293818_ocu6zo.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 0,
        y: 0,
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 560,
        width: 420,
        zIndex: 1,
        isLocked: false,
      },
      {
        id: '900526cb-9ba9-4f6f-9adf-b92af69208b4',
        type: 'text',
        text: 'Drinks',
        fontSize: 28,
        color: '#000000',
        x: 145,
        y: 3.8,
        rotation: 0,
        opacity: 1,
        width: 127,
        height: 39,
        zIndex: 2,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'a65e7893-2d8c-4a10-8f9c-997568249fce',
        type: 'text',
        text: 'Menu',
        fontSize: 24,
        color: '#000000',
        x: 160,
        y: 36,
        rotation: 0,
        opacity: 1,
        width: 94,
        height: 37,
        zIndex: 3,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        type: 'image',
        id: 'tra-dao-cam-sa',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754804219/artshare-asset/design-sample/sample-1/Cascara-cam-sa-mat-ong_nvohuz.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 0,
        y: 80,
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 120,
        width: 120,
        zIndex: 4,
        isLocked: false,
      },
      {
        id: 'tra-dao-cam-sa-text',
        type: 'text',
        text: 'Peach Tea',
        fontSize: 20,
        color: '#000000',
        x: 79,
        y: 118,
        rotation: 0,
        opacity: 1,
        width: 113,
        height: 31,
        zIndex: 5,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'tra-dao-cam-sa-price',
        type: 'text',
        text: '5 $',
        fontSize: 20,
        color: '#E41212',
        x: 80,
        y: 150,
        rotation: 0,
        opacity: 1,
        width: 50,
        height: 28,
        zIndex: 6,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        type: 'image',
        id: 'hoa-hong-vai',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754804227/artshare-asset/design-sample/sample-1/Tra%CC%80-hoa-ho%CC%82%CC%80ng-va%CC%89i-1_ab465o.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 200,
        y: 84,
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 120,
        width: 120,
        zIndex: 7,
        isLocked: false,
      },
      {
        id: 'hoa-hong-vai-text',
        type: 'text',
        text: 'Lychee Tea',
        fontSize: 20,
        color: '#000000',
        x: 282,
        y: 119,
        rotation: 0,
        opacity: 1,
        width: 113,
        height: 31,
        zIndex: 8,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'hoa-hong-vai-price',
        type: 'text',
        text: '4.5 $',
        fontSize: 20,
        color: '#E41212',
        x: 283,
        y: 150,
        rotation: 0,
        opacity: 1,
        width: 50,
        height: 28,
        zIndex: 9,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        type: 'image',
        id: 'sua-chua-da',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754804899/artshare-asset/design-sample/sample-1/Su%CC%9B%CC%83a-chua-da%CC%81-4_hwxlia.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 197,
        y: 207, // 227 → 207
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 120,
        width: 120,
        zIndex: 10,
        isLocked: false,
      },
      {
        id: 'sua-chua-da-text',
        type: 'text',
        text: 'Yogurt',
        fontSize: 20,
        color: '#000000',
        x: 265,
        y: 249, // 269 → 249
        rotation: 0,
        opacity: 1,
        width: 113,
        height: 31,
        zIndex: 11,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'sua-chua-da-price',
        type: 'text',
        text: '5.5 $',
        fontSize: 20,
        color: '#E41212',
        x: 285,
        y: 280, // 300 → 280
        rotation: 0,
        opacity: 1,
        width: 50,
        height: 28,
        zIndex: 12,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        type: 'image',
        id: 'house-tea',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754805131/artshare-asset/design-sample/sample-1/Kfe-house-tea_uzgddm.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 0,
        y: 207, // 227 → 207
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 120,
        width: 120,
        zIndex: 13,
        isLocked: false,
      },
      {
        id: 'house-tea-text',
        type: 'text',
        text: 'Kumquat Tea',
        fontSize: 20,
        color: '#000000',
        x: 92,
        y: 250,
        rotation: 0,
        opacity: 1,
        width: 120,
        height: 31,
        zIndex: 14,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'house-tea-price',
        type: 'text',
        text: '6 $',
        fontSize: 20,
        color: '#E41212',
        x: 82,
        y: 280,
        rotation: 0,
        opacity: 1,
        width: 50,
        height: 28,
        zIndex: 15,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        type: 'image',
        id: 'latte-da',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754808657/artshare-asset/design-sample/sample-1/Latte-da_si4vdj.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 207,
        y: 340,
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 100,
        width: 100,
        zIndex: 16,
        isLocked: false,
      },
      {
        id: 'latte-text',
        type: 'text',
        text: 'Cold Latte',
        fontSize: 20,
        color: '#000000',
        x: 280,
        y: 365,
        rotation: 0,
        opacity: 1,
        width: 113,
        height: 31,
        zIndex: 17,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'latte-price',
        type: 'text',
        text: '7 $',
        fontSize: 20,
        color: '#E41212',
        x: 278,
        y: 390,
        rotation: 0,
        opacity: 1,
        width: 50,
        height: 28,
        zIndex: 18,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        type: 'image',
        id: 'orange-juice',
        src: 'https://res.cloudinary.com/dqxtf297o/image/upload/v1754809442/artshare-asset/design-sample/sample-1/Cam-vat_imvmvt.png',
        zoom: 1,
        opacity: 1,
        flipH: false,
        flipV: false,
        x: 8,
        y: 330,
        rotation: 0,
        brightness: 100,
        contrast: 100,
        saturation: 100,
        hue: 0,
        sepia: 0,
        backgroundColor: '#ffffff',
        height: 110,
        width: 110,
        zIndex: 19,
        isLocked: false,
      },
      {
        id: 'orange-juice-text',
        type: 'text',
        text: 'Orange Juice',
        fontSize: 20,
        color: '#000000',
        x: 92,
        y: 365,
        rotation: 0,
        opacity: 1,
        width: 120,
        height: 31,
        zIndex: 20,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'coldbrew-price',
        type: 'text',
        text: '4.5 $',
        fontSize: 20,
        color: '#E41212',
        x: 88,
        y: 390,
        rotation: 0,
        opacity: 1,
        width: 50,
        height: 28,
        zIndex: 21,
        isLocked: false,
        fontFamily: "'Dancing Script', cursive",
      },
      {
        id: 'phone-number',
        type: 'text',
        text: '+ 123 - 456 - 7890',
        fontSize: 20,
        color: '#000000',
        x: 115,
        y: 480,
        rotation: 0,
        opacity: 1,
        width: 200,
        height: 39,
        zIndex: 22,
        isLocked: false,
        fontFamily: "'DM Serif Text', serif",
      },
      {
        id: 'address',
        type: 'text',
        text: 'Ho Chi Minh City, VietNam',
        fontSize: 20,
        color: '#000000',
        x: 65,
        y: 510,
        rotation: 0,
        opacity: 1,
        width: 300,
        height: 37,
        zIndex: 23,
        isLocked: false,
        fontFamily: "'EB Garamond', serif",
      },
    ],
  },
};
